[package]
name = "clipx"
version = "0.4.0"
edition = "2024"
description = "跨设备剪贴板同步与文件复制工具"
license = "MIT"

[dependencies]
anyhow = "1"
arboard = { version = "3", features = ["wayland-data-control"] }
bincode = "1"
png = "0.17"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"

[[bin]]
name = "clipx"
path = "src/main.rs"

[patch.crates-io]
arboard = { git = "https://github.com/harrisonwang/arboard.git", rev = "3a8ac4af91254af3a5ac8abca6bb3fc0b43470ef" }
